/******CREATE SERCVICES******* */

export const CREATE_SERVICES_START = "CREATE_SERVICES_START";
export const CREATE_SERVICES_PROCESSING = "CREATE_SERVICES_PROCESSING";
export const CREATE_SERVICES_SUCCESS = "CREATE_SERVICES_SUCCESS";
export const CREATE_SERVICES_FAILURE = "CREATE_SERVICES_FAILURE";
export const CREATE_SERVICES_NORESULT = "CREATE_SERVICES_NORESULT";
export const CREATE_SERVICES_INVALIDREQUEST = "CREATE_SERVICES_INVALIDREQUEST";
export const CREATE_SERVICES_INVALIDDATA = "CREATE_SERVICES_INVALIDDATA";
export const CREATE_SERVICES_NOTFOUND = "CREATE_SERVICES_NOTFOUND";
export const CREATE_SERVICES_UNAUTHORIZED = "CREATE_SERVICES_UNAUTHORIZED";
export const CREATE_SERVICES_FORBIDDEN = "CREATE_SERVICES_FORBIDDEN";
export const CREATE_SERVICES_USERSUSPENDED = "CREATE_SERVICES_USERSUSPENDED";
export const CREATE_SERVICES_USERNOTVERIFIED = "CREATE_SERVICES_USERNOTVERIFIED";
export const CREATE_SERVICES_NETWORK_ERROR = "CREATE_SERVICES_NETWORK_ERROR";




/******UPDATE SERCVICES******* */

export const UPDATE_SERVICES_START = "UPDATE_SERVICES_START";
export const UPDATE_SERVICES_PROCESSING = "UPDATE_SERVICES_PROCESSING";
export const UPDATE_SERVICES_SUCCESS = "UPDATE_SERVICES_SUCCESS";
export const UPDATE_SERVICES_FAILURE = "UPDATE_SERVICES_FAILURE";
export const UPDATE_SERVICES_NORESULT = "UPDATE_SERVICES_NORESULT";
export const UPDATE_SERVICES_INVALIDREQUEST = "UPDATE_SERVICES_INVALIDREQUEST";
export const UPDATE_SERVICES_INVALIDDATA = "UPDATE_SERVICES_INVALIDDATA";
export const UPDATE_SERVICES_NOTFOUND = "UPDATE_SERVICES_NOTFOUND";
export const UPDATE_SERVICES_UNAUTHORIZED = "UPDATE_SERVICES_UNAUTHORIZED";
export const UPDATE_SERVICES_FORBIDDEN = "UPDATE_SERVICES_FORBIDDEN";
export const UPDATE_SERVICES_USERSUSPENDED = "UPDATE_SERVICES_USERSUSPENDED";
export const UPDATE_SERVICES_USERNOTVERIFIED = "UPDATE_SERVICES_USERNOTVERIFIED";
export const UPDATE_SERVICES_NETWORK_ERROR = "UPDATE_SERVICES_NETWORK_ERROR";



/******ACTIVATE SERCVICES******* */

export const ACTIVATE_SERVICES_START = "ACTIVATE_SERVICES_START";
export const ACTIVATE_SERVICES_PROCESSING = "ACTIVATE_SERVICES_PROCESSING";
export const ACTIVATE_SERVICES_SUCCESS = "ACTIVATE_SERVICES_SUCCESS";
export const ACTIVATE_SERVICES_FAILURE = "ACTIVATE_SERVICES_FAILURE";
export const ACTIVATE_SERVICES_NORESULT = "ACTIVATE_SERVICES_NORESULT";
export const ACTIVATE_SERVICES_INVALIDREQUEST = "ACTIVATE_SERVICES_INVALIDREQUEST";
export const ACTIVATE_SERVICES_INVALIDDATA = "ACTIVATE_SERVICES_INVALIDDATA";
export const ACTIVATE_SERVICES_NOTFOUND = "ACTIVATE_SERVICES_NOTFOUND";
export const ACTIVATE_SERVICES_UNAUTHORIZED = "ACTIVATE_SERVICES_UNAUTHORIZED";
export const ACTIVATE_SERVICES_FORBIDDEN = "ACTIVATE_SERVICES_FORBIDDEN";
export const ACTIVATE_SERVICES_USERSUSPENDED = "ACTIVATE_SERVICES_USERSUSPENDED";
export const ACTIVATE_SERVICES_USERNOTVERIFIED = "ACTIVATE_SERVICES_USERNOTVERIFIED";
export const ACTIVATE_SERVICES_NETWORK_ERROR = "ACTIVATE_SERVICES_NETWORK_ERROR";



/******DEACTIVATE_SERCVICES******* */


export const DEACTIVATE_SERVICES_START = "DEACTIVATE_SERVICES_START";
export const DEACTIVATE_SERVICES_PROCESSING = "DEACTIVATE_SERVICES_PROCESSING";
export const DEACTIVATE_SERVICES_SUCCESS = "DEACTIVATE_SERVICES_SUCCESS";
export const DEACTIVATE_SERVICES_FAILURE = "DEACTIVATE_SERVICES_FAILURE";
export const DEACTIVATE_SERVICES_NORESULT = "DEACTIVATE_SERVICES_NORESULT";
export const DEACTIVATE_SERVICES_INVALIDREQUEST = "DEACTIVATE_SERVICES_INVALIDREQUEST";
export const DEACTIVATE_SERVICES_INVALIDDATA = "DEACTIVATE_SERVICES_INVALIDDATA";
export const DEACTIVATE_SERVICES_NOTFOUND = "DEACTIVATE_SERVICES_NOTFOUND";
export const DEACTIVATE_SERVICES_UNAUTHORIZED = "DEACTIVATE_SERVICES_UNAUTHORIZED";
export const DEACTIVATE_SERVICES_FORBIDDEN = "DEACTIVATE_SERVICES_FORBIDDEN";
export const DEACTIVATE_SERVICES_USERSUSPENDED = "DEACTIVATE_SERVICES_USERSUSPENDED";
export const DEACTIVATE_SERVICES_USERNOTVERIFIED = "DEACTIVATE_SERVICES_USERNOTVERIFIED";
export const DEACTIVATE_SERVICES_NETWORK_ERROR = "DEACTIVATE_SERVICES_NETWORK_ERROR";



/******DELETE_SERCVICES******* */


export const DELETE_SERVICES_START = "DELETE_SERVICES_START";
export const DELETE_SERVICES_PROCESSING = "DELETE_SERVICES_PROCESSING";
export const DELETE_SERVICES_SUCCESS = "DELETE_SERVICES_SUCCESS";
export const DELETE_SERVICES_FAILURE = "DELETE_SERVICES_FAILURE";
export const DELETE_SERVICES_NORESULT = "DELETE_SERVICES_NORESULT";
export const DELETE_SERVICES_INVALIDREQUEST = "DELETE_SERVICES_INVALIDREQUEST";
export const DELETE_SERVICES_INVALIDDATA = "DELETE_SERVICES_INVALIDDATA";
export const DELETE_SERVICES_NOTFOUND = "DELETE_SERVICES_NOTFOUND";
export const DELETE_SERVICES_UNAUTHORIZED = "DELETE_SERVICES_UNAUTHORIZED";
export const DELETE_SERVICES_FORBIDDEN = "DELETE_SERVICES_FORBIDDEN";
export const DELETE_SERVICES_USERSUSPENDED = "DELETE_SERVICES_USERSUSPENDED";
export const DELETE_SERVICES_USERNOTVERIFIED = "DELETE_SERVICES_USERNOTVERIFIED";
export const DELETE_SERVICES_NETWORK_ERROR = "DELETE_SERVICES_NETWORK_ERROR";


/******GET_SERCVICE******* */


export const GET_SERVICE_START = "GET_SERVICE_START";
export const GET_SERVICE_PROCESSING = "GET_SERVICE_PROCESSING";
export const GET_SERVICE_SUCCESS = "GET_SERVICE_SUCCESS";
export const GET_SERVICE_FAILURE = "GET_SERVICE_FAILURE";
export const GET_SERVICE_NORESULT = "GET_SERVICE_NORESULT";
export const GET_SERVICE_INVALIDREQUEST = "GET_SERVICE_INVALIDREQUEST";
export const GET_SERVICE_INVALIDDATA = "GET_SERVICE_INVALIDDATA";
export const GET_SERVICE_NOTFOUND = "GET_SERVICE_NOTFOUND";
export const GET_SERVICE_UNAUTHORIZED = "GET_SERVICE_UNAUTHORIZED";
export const GET_SERVICE_FORBIDDEN = "GET_SERVICE_FORBIDDEN";
export const GET_SERVICE_USERSUSPENDED = "GET_SERVICE_USERSUSPENDED";
export const GET_SERVICE_USERNOTVERIFIED = "GET_SERVICE_USERNOTVERIFIED";
export const GET_SERVICE_NETWORK_ERROR = "GET_SERVICE_NETWORK_ERROR";



/******GET_SERCVICES******* */


export const GET_SERVICES_START = "GET_SERVICES_START";
export const GET_SERVICES_PROCESSING = "GET_SERVICES_PROCESSING";
export const GET_SERVICES_SUCCESS = "GET_SERVICES_SUCCESS";
export const GET_SERVICES_FAILURE = "GET_SERVICES_FAILURE";
export const GET_SERVICES_NORESULT = "GET_SERVICES_NORESULT";
export const GET_SERVICES_INVALIDREQUEST = "GET_SERVICES_INVALIDREQUEST";
export const GET_SERVICES_INVALIDDATA = "GET_SERVICES_INVALIDDATA";
export const GET_SERVICES_NOTFOUND = "GET_SERVICES_NOTFOUND";
export const GET_SERVICES_UNAUTHORIZED = "GET_SERVICES_UNAUTHORIZED";
export const GET_SERVICES_FORBIDDEN = "GET_SERVICES_FORBIDDEN";
export const GET_SERVICES_USERSUSPENDED = "GET_SERVICES_USERSUSPENDED";
export const GET_SERVICES_USERNOTVERIFIED = "GET_SERVICES_USERNOTVERIFIED";
export const GET_SERVICES_NETWORK_ERROR = "GET_SERVICES_NETWORK_ERROR";
// GET_SERVICES_PAGINATION Actions//
export const GET_SERVICES_PAGINATION_START = "GET_SERVICES_PAGINATION_START";
export const GET_SERVICES_PAGINATION_PROCESSING = "GET_SERVICES_PAGINATION_PROCESSING";
export const GET_SERVICES_PAGINATION_SUCCESS = "GET_SERVICES_PAGINATION_SUCCESS";
export const GET_SERVICES_PAGINATION_NORESULT = "GET_SERVICES_PAGINATION_NORESULT";
export const GET_SERVICES_PAGINATION_NETWORK_ERROR = "GET_SERVICES_PAGINATION_NETWORK_ERROR";



/******GET_MY_SERCVICES******* */

export const GET_MY_SERVICES_START = "GET_MY_SERVICES_START";
export const GET_MY_SERVICES_PROCESSING = "GET_MY_SERVICES_PROCESSING";
export const GET_MY_SERVICES_SUCCESS = "GET_MY_SERVICES_SUCCESS";
export const GET_MY_SERVICES_FAILURE = "GET_MY_SERVICES_FAILURE";
export const GET_MY_SERVICES_NORESULT = "GET_MY_SERVICES_NORESULT";
export const GET_MY_SERVICES_INVALIDREQUEST = "GET_MY_SERVICES_INVALIDREQUEST";
export const GET_MY_SERVICES_INVALIDDATA = "GET_MY_SERVICES_INVALIDDATA";
export const GET_MY_SERVICES_NOTFOUND = "GET_MY_SERVICES_NOTFOUND";
export const GET_MY_SERVICES_UNAUTHORIZED = "GET_MY_SERVICES_UNAUTHORIZED";
export const GET_MY_SERVICES_FORBIDDEN = "GET_MY_SERVICES_FORBIDDEN";
export const GET_MY_SERVICES_USERSUSPENDED = "GET_MY_SERVICES_USERSUSPENDED";
export const GET_MY_SERVICES_USERNOTVERIFIED = "GET_MY_SERVICES_USERNOTVERIFIED";
export const GET_MY_SERVICES_NETWORK_ERROR = "GET_MY_SERVICES_NETWORK_ERROR";
// GET_MY_SERVICES_PAGINATION Actions
export const GET_MY_SERVICES_PAGINATION_START = "GET_MY_SERVICES_PAGINATION_START";
export const GET_MY_SERVICES_PAGINATION_PROCESSING = "GET_MY_SERVICES_PAGINATION_PROCESSING";
export const GET_MY_SERVICES_PAGINATION_SUCCESS = "GET_MY_SERVICES_PAGINATION_SUCCESS";
export const GET_MY_SERVICES_PAGINATION_NORESULT = "GET_MY_SERVICES_PAGINATION_NORESULT";
export const GET_MY_SERVICES_PAGINATION_NETWORK_ERROR = "GET_MY_SERVICES_PAGINATION_NETWORK_ERROR";


/******GET_EST_SERCVICES******* */

export const GET_EST_SERVICES_START = "GET_EST_SERVICES_START";
export const GET_EST_SERVICES_PROCESSING = "GET_EST_SERVICES_PROCESSING";
export const GET_EST_SERVICES_SUCCESS = "GET_EST_SERVICES_SUCCESS";
export const GET_EST_SERVICES_FAILURE = "GET_EST_SERVICES_FAILURE";
export const GET_EST_SERVICES_NORESULT = "GET_EST_SERVICES_NORESULT";
export const GET_EST_SERVICES_INVALIDREQUEST = "GET_EST_SERVICES_INVALIDREQUEST";
export const GET_EST_SERVICES_INVALIDDATA = "GET_EST_SERVICES_INVALIDDATA";
export const GET_EST_SERVICES_NOTFOUND = "GET_EST_SERVICES_NOTFOUND";
export const GET_EST_SERVICES_UNAUTHORIZED = "GET_EST_SERVICES_UNAUTHORIZED";
export const GET_EST_SERVICES_FORBIDDEN = "GET_EST_SERVICES_FORBIDDEN";
export const GET_EST_SERVICES_USERSUSPENDED = "GET_EST_SERVICES_USERSUSPENDED";
export const GET_EST_SERVICES_USERNOTVERIFIED = "GET_EST_SERVICES_USERNOTVERIFIED";
export const GET_EST_SERVICES_NETWORK_ERROR = "GET_EST_SERVICES_NETWORK_ERROR";
// GET_EST_SERVICES_PAGINATION Actions
export const GET_EST_SERVICES_PAGINATION_START = "GET_EST_SERVICES_PAGINATION_START";
export const GET_EST_SERVICES_PAGINATION_PROCESSING = "GET_EST_SERVICES_PAGINATION_PROCESSING";
export const GET_EST_SERVICES_PAGINATION_SUCCESS = "GET_EST_SERVICES_PAGINATION_SUCCESS";
export const GET_EST_SERVICES_PAGINATION_NORESULT = "GET_EST_SERVICES_PAGINATION_NORESULT";
export const GET_EST_SERVICES_PAGINATION_NETWORK_ERROR = "GET_EST_SERVICES_PAGINATION_NETWORK_ERROR";


/******ADD_SERCVICE_IMAGE******* */


export const ADD_SERVICE_IMAGE_START = "ADD_SERVICE_IMAGE_START";
export const ADD_SERVICE_IMAGE_PROCESSING = "ADD_SERVICE_IMAGE_PROCESSING";
export const ADD_SERVICE_IMAGE_SUCCESS = "ADD_SERVICE_IMAGE_SUCCESS";
export const ADD_SERVICE_IMAGE_FAILURE = "ADD_SERVICE_IMAGE_FAILURE";
export const ADD_SERVICE_IMAGE_NORESULT = "ADD_SERVICE_IMAGE_NORESULT";
export const ADD_SERVICE_IMAGE_INVALIDREQUEST = "ADD_SERVICE_IMAGE_INVALIDREQUEST";
export const ADD_SERVICE_IMAGE_INVALIDDATA = "ADD_SERVICE_IMAGE_INVALIDDATA";
export const ADD_SERVICE_IMAGE_NOTFOUND = "ADD_SERVICE_IMAGE_NOTFOUND";
export const ADD_SERVICE_IMAGE_UNAUTHORIZED = "ADD_SERVICE_IMAGE_UNAUTHORIZED";
export const ADD_SERVICE_IMAGE_FORBIDDEN = "ADD_SERVICE_IMAGE_FORBIDDEN";
export const ADD_SERVICE_IMAGE_USERSUSPENDED = "ADD_SERVICE_IMAGE_USERSUSPENDED";
export const ADD_SERVICE_IMAGE_USERNOTVERIFIED = "ADD_SERVICE_IMAGE_USERNOTVERIFIED";
export const ADD_SERVICE_IMAGE_NETWORK_ERROR = "ADD_SERVICE_IMAGE_NETWORK_ERROR";



/******DELETE_SERCVICE_IMAGE******* */

export const DELETE_SERVICE_IMAGE_START = "DELETE_SERVICE_IMAGE_START";
export const DELETE_SERVICE_IMAGE_PROCESSING = "DELETE_SERVICE_IMAGE_PROCESSING";
export const DELETE_SERVICE_IMAGE_SUCCESS = "DELETE_SERVICE_IMAGE_SUCCESS";
export const DELETE_SERVICE_IMAGE_FAILURE = "DELETE_SERVICE_IMAGE_FAILURE";
export const DELETE_SERVICE_IMAGE_NORESULT = "DELETE_SERVICE_IMAGE_NORESULT";
export const DELETE_SERVICE_IMAGE_INVALIDREQUEST = "DELETE_SERVICE_IMAGE_INVALIDREQUEST";
export const DELETE_SERVICE_IMAGE_INVALIDDATA = "DELETE_SERVICE_IMAGE_INVALIDDATA";
export const DELETE_SERVICE_IMAGE_NOTFOUND = "DELETE_SERVICE_IMAGE_NOTFOUND";
export const DELETE_SERVICE_IMAGE_UNAUTHORIZED = "DELETE_SERVICE_IMAGE_UNAUTHORIZED";
export const DELETE_SERVICE_IMAGE_FORBIDDEN = "DELETE_SERVICE_IMAGE_FORBIDDEN";
export const DELETE_SERVICE_IMAGE_USERSUSPENDED = "DELETE_SERVICE_IMAGE_USERSUSPENDED";
export const DELETE_SERVICE_IMAGE_USERNOTVERIFIED = "DELETE_SERVICE_IMAGE_USERNOTVERIFIED";
export const DELETE_SERVICE_IMAGE_NETWORK_ERROR = "DELETE_SERVICE_IMAGE_NETWORK_ERROR";



/******GET_SERCVICE_IMAGE******* */


export const GET_SERVICE_IMAGE_START = "GET_SERVICE_IMAGE_START";
export const GET_SERVICE_IMAGE_PROCESSING = "GET_SERVICE_IMAGE_PROCESSING";
export const GET_SERVICE_IMAGE_SUCCESS = "GET_SERVICE_IMAGE_SUCCESS";
export const GET_SERVICE_IMAGE_FAILURE = "GET_SERVICE_IMAGE_FAILURE";
export const GET_SERVICE_IMAGE_NORESULT = "GET_SERVICE_IMAGE_NORESULT";
export const GET_SERVICE_IMAGE_INVALIDREQUEST = "GET_SERVICE_IMAGE_INVALIDREQUEST";
export const GET_SERVICE_IMAGE_INVALIDDATA = "GET_SERVICE_IMAGE_INVALIDDATA";
export const GET_SERVICE_IMAGE_NOTFOUND = "GET_SERVICE_IMAGE_NOTFOUND";
export const GET_SERVICE_IMAGE_UNAUTHORIZED = "GET_SERVICE_IMAGE_UNAUTHORIZED";
export const GET_SERVICE_IMAGE_FORBIDDEN = "GET_SERVICE_IMAGE_FORBIDDEN";
export const GET_SERVICE_IMAGE_USERSUSPENDED = "GET_SERVICE_IMAGE_USERSUSPENDED";
export const GET_SERVICE_IMAGE_USERNOTVERIFIED = "GET_SERVICE_IMAGE_USERNOTVERIFIED";
export const GET_SERVICE_IMAGE_NETWORK_ERROR = "GET_SERVICE_IMAGE_NETWORK_ERROR";